---
- name: Install NCCL from CUDA repository for RHEL
  ansible.builtin.yum:
    name:
      - "libnccl-{{ nccl_package_version }}"
      - "libnccl-devel-{{ nccl_package_version }}"
      - "libnccl-static-{{ nccl_package_version }}"
    state: present
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when:
    - ansible_os_family == 'RedHat'

- name: Install NCCL from CUDA repository for Ubuntu
  ansible.builtin.apt:
    name:
      - "libnccl2={{ nccl_package_version }}"
      - "libnccl-dev={{ nccl_package_version }}"
    state: present
    lock_timeout: 300
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  when:
    - ansible_distribution == 'Ubuntu'
