- name: Include tasks for Ubuntu
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Include tasks for RedHat
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
