---
- name: Kernel limits
  when: >
    (ansible_os_family == 'RedHat') or (ansible_distribution == 'Ubuntu')

  block:

    - name: Ensure kernel limits file exists
      ansible.builtin.file:
        path: /etc/security/limits.d/50-hpc-limits.conf
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Ensure kernel limits are configured
      ansible.builtin.lineinfile:
        path: /etc/security/limits.d/50-hpc-limits.conf
        regexp: '^\*\s+{{ item.type }}\s+{{ item.name }}\s+(?!.*\b{{ item.limit }}\b).*$'
        line: '*  {{ item.type }}  {{ item.name }}  {{ item.limit }}'
      loop: "{{ kernel_limits_default }}"
      when:
        - "'amd' not in options"

    - name: Ensure kernel limits are configured
      ansible.builtin.lineinfile:
        path: /etc/security/limits.d/50-hpc-limits.conf
        regexp: '^\*\s+{{ item.type }}\s+{{ item.name }}\s+(?!.*\b{{ item.limit }}\b).*$'
        line: '*  {{ item.type }}  {{ item.name }}  {{ item.limit }}'
      loop: "{{ kernel_limits_amd }}"
      when:
        - "'amd' in options"
