- name: Import tasks for Ubuntu
  ansible.builtin.include_tasks:
    file: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Import tasks for EL
  ansible.builtin.include_tasks:
    file: el.yml
  when: ansible_os_family == 'RedHat'
