---
- name: Install CUDA Samples
  vars:
    user: "{{ ansible_user }}"
  block:
    - name: Create CUDA Samples directory
      ansible.builtin.file:
        path: "{{ benchmark_base_path }}/cuda-samples"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true

    - name: Clone CUDA Samples
      ansible.builtin.git:
        repo: "{{ cuda_samples_repo }}"
        dest: "{{ benchmark_base_path }}/cuda-samples"
        force: true
        version: "{{ cuda_samples_version | default('master') }}"
      become_user: "{{ user }}"
      become: true

    # - name: Build CUDA Samples
    #   environment:
    #     MAKEFLAGS: "-j 16"
    #   community.general.make:
    #     chdir: "{{ benchmark_base_path }}/cuda-samples"
    #     params:
    #       SMS: "80 90"
    #   become_user: "{{ user }}"
    #   become: true
