# cmake is needed by cuda-samples
---
- name: Install dependencies
  ansible.builtin.yum:
    name:
      - git
      - cmake
      - pciutils
      - pciutils-devel
  become: true
  when: ansible_os_family == 'RedHat'
