---

- name: Configure RHCK
  ansible.builtin.include_tasks: rhck.yml
  when:
    - "options is defined"
    - "'rhck' in options"
    - ansible_os_family == 'RedHat'
    - ansible_distribution == 'OracleLinux'

- name: Configure Ubuntu Kernel
  ansible.builtin.include_tasks: ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22'
