---
- name: Increase Max Sessions connection limit
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^MaxSessions'
    line: 'MaxSessions 100'
    state: present

- name: Increase Max Startups connection limit
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^MaxStartups'
    line: 'MaxStartups 100'
    state: present
