---
- name: Install oci-utils image clean for CentOS 7 and Ubuntu 20
  when:
    - ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'Ubuntu' )

  block:
    - name: Install oci-image-cleanup
      ansible.builtin.copy:
        src: "oci-image-cleanup.{{ ansible_distribution }}"
        dest: /usr/libexec/oci-image-cleanup
        owner: "root"
        group: "root"
        mode: "0755"
