---
- name: Install tuned via yum
  ansible.builtin.yum:
    name: tuned
    state: present

- name: Start tuned
  ansible.builtin.service:
    name: tuned
    state: started
    enabled: true

- name: Start-profile # noqa no-changed-when
  ansible.builtin.command: |
    tuned-adm profile throughput-performance
