---
- name: Install tuned via apt
  ansible.builtin.apt:
    name: tuned
    state: present
    update_cache: true
    lock_timeout: 300
  ignore_errors: true
  register: ignore_errors_register

- name: Start tuned
  ansible.builtin.service:
    name: tuned
    state: started
    enabled: true

- name: Start-profile # noqa no-changed-when command-instead-of-shell
  ansible.builtin.command: |
    tuned-adm profile throughput-performance
