- name: Packages for RPM systems
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Packages for DEB systems
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
