nvidia_driver_package_state: present
nvidia_driver_package_version: ''
nvidia_driver_persistence_mode_on: true
nvidia_driver_skip_reboot: true
nvidia_driver_module_file: /etc/modprobe.d/nvidia.conf
nvidia_driver_module_params: ''
nvidia_driver_add_repos: true
nvidia_driver_branch: "470"
nvidia_repo_redhat_gpgkey: "D42D0685"
nvidia_repo_ubuntu_gpgkey: "3bf863cc"


##############################################################################
# RedHat family                                                              #
##############################################################################
epel_package: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
nvidia_driver_rhel_cuda_repo_baseurl: "https://developer.download.nvidia.com/compute/cuda/repos/{{ _rhel_repo_dir }}/"
nvidia_driver_rhel_cuda_repo_gpgkey: "https://developer.download.nvidia.com/compute/cuda/repos/{{ _rhel_repo_dir }}/{{ nvidia_repo_redhat_gpgkey }}.pub"

nvidia_driver_rhel_branch: "{{ nvidia_driver_branch }}"


##############################################################################
# Ubuntu                                                                     #
##############################################################################

# Driver branch to install with Ubuntu
nvidia_driver_ubuntu_branch: "{{ nvidia_driver_branch }}"

# Determine if we should install from CUDA repo instead of Canonical repos
nvidia_driver_ubuntu_install_from_cuda_repo: true

# Installing with Canonical repositories
nvidia_driver_ubuntu_packages:
  - "nvidia-headless-{{ nvidia_driver_ubuntu_branch }}-server"
  - "nvidia-utils-{{ nvidia_driver_ubuntu_branch }}-server"
  - "nvidia-headless-no-dkms-{{ nvidia_driver_ubuntu_branch }}-server"
  - "nvidia-kernel-source-{{ nvidia_driver_ubuntu_branch }}-server"

# Installing with CUDA repositories
nvidia_driver_ubuntu_cuda_repo_gpgkey_url: "https://developer.download.nvidia.com/compute/cuda/repos/{{ _ubuntu_repo_dir }}/{{ nvidia_repo_ubuntu_gpgkey }}.pub"
nvidia_driver_ubuntu_cuda_repo_gpgkey_id: "{{ nvidia_repo_ubuntu_gpgkey }}"
nvidia_driver_ubuntu_cuda_repo_baseurl: "https://developer.download.nvidia.com/compute/cuda/repos/{{ _ubuntu_repo_dir }}"
nvidia_driver_ubuntu_cuda_package: "cuda-drivers-fabricmanager"
