---
- name: Run grub2-mkconfig # noqa no-changed-when
  ansible.builtin.command: >-
    grub2-mkconfig {{ '--update-bls-cmdline ' if (ansible_distribution_major_version | int > 8) else '' }}-o /etc/grub2-efi.cfg
- name: Run update-grub # noqa no-changed-when
  ansible.builtin.command: update-grub
