---
- name: Install openmpi
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version == '22' or ansible_distribution_major_version == '24'
  block:
    - name: Install OpenMPI packages
      ansible.builtin.apt:
        name:
          - openmpi-bin
          - openmpi-common
          - libopenmpi-dev
        lock_timeout: 300
