---
- name: Install rccl tests
  block:
    - name: Clone rccl github repository
      ansible.builtin.git:
        repo: https://github.com/ROCm/rccl.git
        dest: /opt/rccl
        clone: true
        update: true
        version: "{{amd_rccl_commit}}"

    - name: Creates /opt/rccl/build directory
      ansible.builtin.file:
        path: /opt/rccl/build
        state: directory
        mode: "0755"

    - name: Install libstdc++-12-dev
      ansible.builtin.apt:
        name:
          - libstdc++-12-dev
          - wget
          - gnupg
        lock_timeout: 300
      when: ansible_distribution == 'Ubuntu'

    - name: Download Kitware APT repository key on control
      delegate_to: localhost
      run_once: true
      ansible.builtin.get_url:
        url: https://apt.kitware.com/keys/kitware-archive-latest.asc
        dest: /tmp/kitware-archive-latest.asc
        mode: '0644'
        validate_certs: no
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version == '22'

    - name: Copy Kitware APT key into trusted.gpg.d
      ansible.builtin.copy:
        src: /tmp/kitware-archive-latest.asc
        dest: /etc/apt/trusted.gpg.d/kitware.asc
        mode: '0644'
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version == '22'

    - name: Add Kitware APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kitware.com/ubuntu/ {{ ansible_distribution_release }} main"
        state: present
        filename: kitware
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '22'

    - name: Install cmake
      ansible.builtin.apt:
        name: cmake
        state: latest
        lock_timeout: 300
      when: ansible_distribution == 'Ubuntu'

    - name: Install OL dependencies
      ansible.builtin.yum:
        name:
          - cmake
          - libstdc++-devel
      become: true
      when: ansible_os_family == 'RedHat'

    # - name: Set up CXX # noqa no-changed-when
    #   ansible.builtin.shell: |
    #     CXX=/opt/rocm/bin/hipcc cmake -DCMAKE_PREFIX_PATH=/opt/rocm/ ..
    #   args:
    #     chdir: "/opt/rccl/build"

    - name: Kick off CMake configure and log to disk
      shell: |
        cd /opt/rccl/build && \
        CXX=/opt/rocm/bin/hipcc \
        cmake -DCMAKE_PREFIX_PATH=/opt/rocm .. \
        2>&1 | tee /var/log/rccl_configure.log
      async: 600
      poll: 0
      register: cmake_job

    - name: Wait for CMake configure to finish
      ansible.builtin.async_status:
        jid: "{{ cmake_job.ansible_job_id }}"
      register: cmake_status
      until: cmake_status.finished
      retries: 10
      delay: 30  # poll every 30s, up to 10×30s = 5m

    - name: Show the last 20 lines of CMakeOutput.log
      ansible.builtin.shell: tail -n 20 /opt/rccl/build/CMakeFiles/CMakeOutput.log || true
      register: cmake_excerpt
      ignore_errors: true

    - name: Debug CMake excerpt
      ansible.builtin.debug:
        var: cmake_excerpt.stdout_lines

    # - name: Make rccl
    #   community.general.make:
    #     chdir: "/opt/rccl/build"
    #     params:
    #       NUM_THREADS: "{{ ansible_processor_vcpus }}"

    - name: Find matching directories
      ansible.builtin.find:
        paths: /usr/mpi/gcc/
        patterns: "openmpi*"
        file_type: directory
      register: openmpi_dirs

    - name: Clone rccl tests
      ansible.builtin.git:
        repo: https://github.com/ROCm/rccl-tests.git
        dest: /opt/rccl-tests
        clone: true
        update: true
        version: 52aee698fa255c1eb081d1f33368cca1a82b1b67

    - name: Create symlink from openmpi /lib64 to /lib as rccl test build expects /lib
      command: ln -s {{openmpi_dirs.files[0].path}}/lib64 {{openmpi_dirs.files[0].path}}/lib
      when: ansible_os_family == 'RedHat'

    - name: Make RCCL test
      community.general.make:
        chdir: "/opt/rccl-tests"
        params:
          MPI=1
          MPI_HOME={{openmpi_dirs.files[0].path}}
          NCCL_HOME=/opt/rccl
          HIP_HOME=/opt/rocm
