---
# OL platform images come with oci-utils installed, which includes the
# oci-growfs tool which can be used to grow the root filesystem when
# an instance is launched with a larger bootvolume.
#
# See https://docs.oracle.com/en-us/iaas/oracle-linux/oci-utils/index.htm#oci-growfs

- name: Resize Root FS # noqa no-changed-when
  ansible.builtin.command: /usr/libexec/oci-growfs -y
  when: ansible_os_family == 'RedHat'

- name: Resize Root FS # noqa no-changed-when
  ansible.builtin.command: growpart /dev/sda 1
  when: ansible_os_family == "Debian"
  ignore_errors: true

- name: Resize Root FS # noqa no-changed-when
  ansible.builtin.command: resize2fs /dev/sda1
  when: ansible_os_family == "Debian"
  ignore_errors: true