- name: Install specific version of OCI Cloud Agent on Ubuntu from Snapcraft
  when: ansible_distribution == 'Ubuntu' and oci_cloud_agent_channel_ubuntu is defined

# version format for Ubuntu
# oci_cloud_agent_version: 1.40.0-12

  block:
    - name: Install Oracle Cloud Agent Snap from channel
      community.general.snap:
        name: oracle-cloud-agent
        channel: "{{ oci_cloud_agent_channel_ubuntu }}"
        state: present

- name: Install specific version of OCI Clud Agent on Ubuntu from URL
  when: ansible_distribution == 'Ubuntu' and oci_cloud_agent_version_ubuntu is defined and oca_download_url is defined

# version format for Ubuntu
# oca_download_url: https://objectstorage.us-phoenix-1.oraclecloud.com/p/.../n/.../b/agent_test/o/1.40.0/2/
# oci_cloud_agent_version: 1.40.0-12

  block:
    - name: Get DEB architecture # noqa no-changed-when
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture

    - name: Download Oracle Cloud Agent Snap on control
      delegate_to: localhost
      run_once: true
      ansible.builtin.get_url:
        url: "{{ oca_download_url }}oracle-cloud-agent_{{ oci_cloud_agent_version_ubuntu }}_{{ deb_architecture.stdout }}.snap"
        dest: "/tmp/oracle-cloud-agent_{{ oci_cloud_agent_version_ubuntu }}_{{ deb_architecture.stdout }}.snap"
        mode: "0755"
        validate_certs: no
      register: oca_snap_control

    - name: Copy Oracle Cloud Agent Snap to builder VM
      ansible.builtin.copy:
        src: "{{ oca_snap_control.dest }}"
        dest: "{{ oca_snap_control.dest }}"
        mode: "0755"

    - name: Install Oracle Cloud Agent Snap from URL # noqa no-changed-when
      ansible.builtin.command: >
        snap install {{ oca_snap_control.dest }} --dangerous --classic


- name: Stop Oracle Cloud Agent (Ubuntu)
  ansible.builtin.systemd:
    name: snap.oracle-cloud-agent.oracle-cloud-agent
    state: stopped
    enabled: false
    no_block: true
  when: ansible_distribution == 'Ubuntu'

- name: Stop Oracle Cloud Updater (Ubuntu)
  ansible.builtin.systemd:
    name: snap.oracle-cloud-agent.oracle-cloud-agent-updater
    state: stopped
    enabled: false
    no_block: true
  when: ansible_distribution == 'Ubuntu'
